use_frameworks!

platform :ios, '9.0'

target 'MyPodTestPro_Example' do
  pod 'MyPodTestPro', :path => '../'

  target 'MyPodTestPro_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
